{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "e824d841-b770-417f-8238-96818a442ec2",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Title</th>\n",
       "      <th>WG Type</th>\n",
       "      <th>City/District</th>\n",
       "      <th>Street</th>\n",
       "      <th>Price</th>\n",
       "      <th>Availability</th>\n",
       "      <th>Size</th>\n",
       "      <th>Owner</th>\n",
       "      <th>Online Duration</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Zimmer in Charlottenburger 2er WG am Lietzense...</td>\n",
       "      <td>2er WG</td>\n",
       "      <td>Charlottenburg</td>\n",
       "      <td>Philippistr. 11</td>\n",
       "      <td>650 €</td>\n",
       "      <td>01.08.2024\\n\\n-30.06.2025</td>\n",
       "      <td>12 m²</td>\n",
       "      <td>Lukas Sonnabend</td>\n",
       "      <td>Online: 6 Minuten</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Teilmöbliertes 15m² Zimmer in Prenzlauer Berg</td>\n",
       "      <td>2er WG</td>\n",
       "      <td>Prenzlauer Berg</td>\n",
       "      <td>Schönfließer Str</td>\n",
       "      <td>600 €</td>\n",
       "      <td>15.07.2024</td>\n",
       "      <td>15 m²</td>\n",
       "      <td>Sal</td>\n",
       "      <td>Online: 8 Minuten</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>140 cm2 WG, Balkon, wunderschöne Kreuzberger L...</td>\n",
       "      <td>3er WG</td>\n",
       "      <td></td>\n",
       "      <td>Yorkstr. 77</td>\n",
       "      <td>750 €</td>\n",
       "      <td>01.08.2024</td>\n",
       "      <td>12 m²</td>\n",
       "      <td>Darwin</td>\n",
       "      <td>Online: 9 Minuten</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>WG-Zimmer in 2er-WG auf Zeit</td>\n",
       "      <td>2er WG</td>\n",
       "      <td>Wilmersdorf</td>\n",
       "      <td>Aachener Straße</td>\n",
       "      <td>523 €</td>\n",
       "      <td>01.08.2024\\n\\n-15.01.2025</td>\n",
       "      <td>20 m²</td>\n",
       "      <td>Sandra L.</td>\n",
       "      <td>Online: 10 Minuten</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>25qm -  großes  Zimmer  in  Kreuzberg für 1 Pe...</td>\n",
       "      <td>4er WG</td>\n",
       "      <td>Kreuzberg</td>\n",
       "      <td>Dieffenbachstr.</td>\n",
       "      <td>650 €</td>\n",
       "      <td>14.07.2024\\n\\n-30.05.2025</td>\n",
       "      <td>25 m²</td>\n",
       "      <td>M NEÜFF</td>\n",
       "      <td>Online: 11 Minuten</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>195</th>\n",
       "      <td>Zimmer in Charlottenburger 2er WG am Lietzense...</td>\n",
       "      <td>2er WG</td>\n",
       "      <td>Charlottenburg</td>\n",
       "      <td>Philippistr. 11</td>\n",
       "      <td>650 €</td>\n",
       "      <td>01.08.2024\\n\\n-30.06.2025</td>\n",
       "      <td>12 m²</td>\n",
       "      <td>Lukas Sonnabend</td>\n",
       "      <td>Online: 6 Minuten</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>196</th>\n",
       "      <td>Teilmöbliertes 15m² Zimmer in Prenzlauer Berg</td>\n",
       "      <td>2er WG</td>\n",
       "      <td>Prenzlauer Berg</td>\n",
       "      <td>Schönfließer Str</td>\n",
       "      <td>600 €</td>\n",
       "      <td>15.07.2024</td>\n",
       "      <td>15 m²</td>\n",
       "      <td>Sal</td>\n",
       "      <td>Online: 9 Minuten</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>197</th>\n",
       "      <td>140 cm2 WG, Balkon, wunderschöne Kreuzberger L...</td>\n",
       "      <td>3er WG</td>\n",
       "      <td></td>\n",
       "      <td>Yorkstr. 77</td>\n",
       "      <td>750 €</td>\n",
       "      <td>01.08.2024</td>\n",
       "      <td>12 m²</td>\n",
       "      <td>Darwin</td>\n",
       "      <td>Online: 10 Minuten</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>198</th>\n",
       "      <td>WG-Zimmer in 2er-WG auf Zeit</td>\n",
       "      <td>2er WG</td>\n",
       "      <td>Wilmersdorf</td>\n",
       "      <td>Aachener Straße</td>\n",
       "      <td>523 €</td>\n",
       "      <td>01.08.2024\\n\\n-15.01.2025</td>\n",
       "      <td>20 m²</td>\n",
       "      <td>Sandra L.</td>\n",
       "      <td>Online: 10 Minuten</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>199</th>\n",
       "      <td>Privatzimmer zu vermieten in Berlin</td>\n",
       "      <td>2er WG</td>\n",
       "      <td>Schöneberg</td>\n",
       "      <td>Pallasstraße</td>\n",
       "      <td>450 €</td>\n",
       "      <td>01.01.2025</td>\n",
       "      <td>m²</td>\n",
       "      <td>Spotahome</td>\n",
       "      <td>Online: 1 Stunde</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>200 rows × 9 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                 Title WG Type  \\\n",
       "0    Zimmer in Charlottenburger 2er WG am Lietzense...  2er WG   \n",
       "1        Teilmöbliertes 15m² Zimmer in Prenzlauer Berg  2er WG   \n",
       "2    140 cm2 WG, Balkon, wunderschöne Kreuzberger L...  3er WG   \n",
       "3                         WG-Zimmer in 2er-WG auf Zeit  2er WG   \n",
       "4    25qm -  großes  Zimmer  in  Kreuzberg für 1 Pe...  4er WG   \n",
       "..                                                 ...     ...   \n",
       "195  Zimmer in Charlottenburger 2er WG am Lietzense...  2er WG   \n",
       "196      Teilmöbliertes 15m² Zimmer in Prenzlauer Berg  2er WG   \n",
       "197  140 cm2 WG, Balkon, wunderschöne Kreuzberger L...  3er WG   \n",
       "198                       WG-Zimmer in 2er-WG auf Zeit  2er WG   \n",
       "199                Privatzimmer zu vermieten in Berlin  2er WG   \n",
       "\n",
       "       City/District            Street  Price               Availability  \\\n",
       "0     Charlottenburg   Philippistr. 11  650 €  01.08.2024\\n\\n-30.06.2025   \n",
       "1    Prenzlauer Berg  Schönfließer Str  600 €                 15.07.2024   \n",
       "2                          Yorkstr. 77  750 €                 01.08.2024   \n",
       "3        Wilmersdorf   Aachener Straße  523 €  01.08.2024\\n\\n-15.01.2025   \n",
       "4          Kreuzberg   Dieffenbachstr.  650 €  14.07.2024\\n\\n-30.05.2025   \n",
       "..               ...               ...    ...                        ...   \n",
       "195   Charlottenburg   Philippistr. 11  650 €  01.08.2024\\n\\n-30.06.2025   \n",
       "196  Prenzlauer Berg  Schönfließer Str  600 €                 15.07.2024   \n",
       "197                        Yorkstr. 77  750 €                 01.08.2024   \n",
       "198      Wilmersdorf   Aachener Straße  523 €  01.08.2024\\n\\n-15.01.2025   \n",
       "199       Schöneberg      Pallasstraße  450 €                 01.01.2025   \n",
       "\n",
       "      Size            Owner     Online Duration  \n",
       "0    12 m²  Lukas Sonnabend   Online: 6 Minuten  \n",
       "1    15 m²              Sal   Online: 8 Minuten  \n",
       "2    12 m²           Darwin   Online: 9 Minuten  \n",
       "3    20 m²        Sandra L.  Online: 10 Minuten  \n",
       "4    25 m²          M NEÜFF  Online: 11 Minuten  \n",
       "..     ...              ...                 ...  \n",
       "195  12 m²  Lukas Sonnabend   Online: 6 Minuten  \n",
       "196  15 m²              Sal   Online: 9 Minuten  \n",
       "197  12 m²           Darwin  Online: 10 Minuten  \n",
       "198  20 m²        Sandra L.  Online: 10 Minuten  \n",
       "199     m²        Spotahome    Online: 1 Stunde  \n",
       "\n",
       "[200 rows x 9 columns]"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "import pandas as pd\n",
    "import time\n",
    "\n",
    "def get_wg_listings(url):\n",
    "    headers = {\n",
    "        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'\n",
    "    }\n",
    "    response = requests.get(url, headers=headers)\n",
    "    soup = BeautifulSoup(response.content, 'html.parser')\n",
    "    return soup\n",
    "\n",
    "def parse_listing(listing):\n",
    "    title = listing.find('h3', class_='truncate_title noprint')\n",
    "    location = listing.find('div', class_='col-xs-11')\n",
    "    price = listing.find('div', class_='col-xs-3')\n",
    "    availability = listing.find('div', class_='col-xs-5 text-center')\n",
    "    size = listing.find('div', class_='col-xs-3 text-right')\n",
    "\n",
    "    # Using BeautifulSoup to locate owner and online duration\n",
    "    owner = listing.find('span', class_='ml5')\n",
    "    online_duration = listing.find('span', style='color: #218700;')\n",
    "\n",
    "    # Extracting location information\n",
    "    location_text = location.text.strip() if location else None\n",
    "    wg_type, district, street = None, None, None\n",
    "\n",
    "    if location_text:\n",
    "        location_parts = [part.strip() for part in location_text.split(\"|\")]\n",
    "        if len(location_parts) == 3:\n",
    "            wg_type, city_district, street = location_parts\n",
    "        elif len(location_parts) == 2:\n",
    "            wg_type, city_district = location_parts\n",
    "        elif len(location_parts) == 1:\n",
    "            wg_type = location_parts[0]\n",
    "\n",
    "        if city_district and \"Berlin\" in city_district:\n",
    "            district = city_district.replace(\"Berlin\", \"\").strip()\n",
    "\n",
    "    # Remove extra spaces between dates in availability\n",
    "    availability_text = availability.text.strip().replace(' ', '') if availability else None\n",
    "\n",
    "    data = {\n",
    "        'Title': title.text.strip() if title else None,\n",
    "        'WG Type': wg_type,\n",
    "        'City/District': district,\n",
    "        'Street': street,\n",
    "        'Price': f\"{price.text.strip().replace('€', '').replace(' ', '')} €\" if price else None,\n",
    "        'Availability': availability_text,\n",
    "        'Size': f\"{size.text.strip().replace('m²', '').replace(' ', '')} m²\" if size else None,\n",
    "        'Owner': owner.text.strip() if owner else None,\n",
    "        'Online Duration': online_duration.text.strip() if online_duration else None\n",
    "    }\n",
    "\n",
    "    return data\n",
    "\n",
    "def scrape_wg_data(base_url, num_listings):\n",
    "    listings_data = []\n",
    "    page = 0\n",
    "\n",
    "    while len(listings_data) < num_listings:\n",
    "        url = f\"{base_url}?page={page}\"\n",
    "        soup = get_wg_listings(url)\n",
    "        listings = soup.find_all('div', class_='offer_list_item')\n",
    "        \n",
    "        if not listings:\n",
    "            break\n",
    "\n",
    "        for listing in listings:\n",
    "            data = parse_listing(listing)\n",
    "            listings_data.append(data)\n",
    "            if len(listings_data) >= num_listings:\n",
    "                break\n",
    "\n",
    "        page += 1\n",
    "        time.sleep(1)  # To avoid overwhelming the server with requests\n",
    "\n",
    "    df = pd.DataFrame(listings_data)\n",
    "    return df\n",
    "\n",
    "# Scrape data\n",
    "BASE_URL = 'https://www.wg-gesucht.de/wg-zimmer-in-Berlin.8.0.1.0.html'\n",
    "NUM_LISTINGS = 200\n",
    "wg_data_df = scrape_wg_data(BASE_URL, NUM_LISTINGS)\n",
    "wg_data_df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "55b529ab-c210-4af8-8288-b254b4af1728",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
